/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tetris2024;

/**
 *
 * @author marcel
 */
public class ScoreBoard extends javax.swing.JPanel implements ScoreInterface{
    

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        reset();
        
    }
    
    public void incrementScore() {
        int currentScore = ConfingData.getInstance().getScore() + 1;
        ConfingData.getInstance().setScore(currentScore);
        updateScoreLabel();
    }
    
    public void reset() {
        ConfingData.getInstance().setScore(0);
        updateScoreLabel();
    }
    
    private void updateScoreLabel() {
        jLabelScore.setText("" + ConfingData.getInstance().getScore());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelScore = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));

        jLabelScore.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabelScore)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelScore)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelScore;
    // End of variables declaration//GEN-END:variables
}
